# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Calm Meditation
email: tom@idratherbewriting.com
baseurl: /calm-meditation
url: http://idratherbewriting.com
baseurl_media: http://idratherassets.com/calm_meditation
github_username:  tomjohnson1492

# Build settings
markdown: kramdown
theme: minima
permalink: /:title/
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-paginate]

exclude:
  - Gemfile
  - Gemfile.lock

description: >
  Contains short videos capturing still scenes from nature with a music background,
  intended for calming or meditation purposes. When you're stressed out or upset, watch
  a few videos. As your mind focuses on the small details, let your worries and frustrations
  float away. The purpose is not to entertain or to distract, but to help calm, soothe, and
  surface your inner quiet. The videos contain scenes from the San Tomas Aquinas trail
  in Santa Clara, California.
